# Generated by Django 3.2 on 2021-06-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('transaction_n', models.CharField(max_length=255, unique=True)),
                ('transaction_status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('CLOSE', 'CLOSE')], max_length=255)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.branchmaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.companyledgermaster')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.departmentmaster')),
            ],
        ),
    ]
