# Generated by Django 3.2 on 2021-06-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLineItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('required_on_date', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rate_per_unit', models.IntegerField()),
                ('unit', models.CharField(choices=[('KG', 'METER'), ('KG', 'METER')], max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.articlemaster')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.colormaster')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.transaction')),
            ],
        ),
    ]
