# Generated by Django 3.2 on 2021-06-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transactionlineitemdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('gross_quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('net_quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('unit', models.CharField(choices=[('KG', 'METER'), ('KG', 'METER')], max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.articlemaster')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.colormaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.companyledgermaster')),
                ('transactionlineitemdetails_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.transactionlineitemdetails')),
            ],
        ),
    ]
