# Generated by Django 3.2 on 2021-07-05 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20210702_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_n',
            new_name='transaction_id',
        ),
    ]
